on: [push]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

  build:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo "TODO"

